//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm_CSharp_hw2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinForm_CSharp_hw2.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string en_amount {
            get {
                return ResourceManager.GetString("en_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafe.
        /// </summary>
        internal static string en_cafe {
            get {
                return ResourceManager.GetString("en_cafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string en_calculate {
            get {
                return ResourceManager.GetString("en_calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coca-cola.
        /// </summary>
        internal static string en_coca {
            get {
                return ResourceManager.GetString("en_coca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color application.
        /// </summary>
        internal static string en_colorform {
            get {
                return ResourceManager.GetString("en_colorform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string en_cost {
            get {
                return ResourceManager.GetString("en_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas station.
        /// </summary>
        internal static string en_gasstation {
            get {
                return ResourceManager.GetString("en_gasstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamburger.
        /// </summary>
        internal static string en_hamburger {
            get {
                return ResourceManager.GetString("en_hamburger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot-dog.
        /// </summary>
        internal static string en_hot_dog {
            get {
                return ResourceManager.GetString("en_hot_dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lit..
        /// </summary>
        internal static string en_liters {
            get {
                return ResourceManager.GetString("en_liters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string en_num {
            get {
                return ResourceManager.GetString("en_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of oil.
        /// </summary>
        internal static string en_oil {
            get {
                return ResourceManager.GetString("en_oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French fries.
        /// </summary>
        internal static string en_potato {
            get {
                return ResourceManager.GetString("en_potato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rub..
        /// </summary>
        internal static string en_rub {
            get {
                return ResourceManager.GetString("en_rub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string en_settings {
            get {
                return ResourceManager.GetString("en_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To issue.
        /// </summary>
        internal static string en_toissue {
            get {
                return ResourceManager.GetString("en_toissue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pay.
        /// </summary>
        internal static string en_topay {
            get {
                return ResourceManager.GetString("en_topay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total payable.
        /// </summary>
        internal static string en_totalpay {
            get {
                return ResourceManager.GetString("en_totalpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        internal static string ru_amount {
            get {
                return ResourceManager.GetString("ru_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафе.
        /// </summary>
        internal static string ru_cafe {
            get {
                return ResourceManager.GetString("ru_cafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассчитать.
        /// </summary>
        internal static string ru_calculate {
            get {
                return ResourceManager.GetString("ru_calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кока-кола.
        /// </summary>
        internal static string ru_coca {
            get {
                return ResourceManager.GetString("ru_coca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет окна.
        /// </summary>
        internal static string ru_colorform {
            get {
                return ResourceManager.GetString("ru_colorform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        internal static string ru_cost {
            get {
                return ResourceManager.GetString("ru_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автозаправка.
        /// </summary>
        internal static string ru_gasstation {
            get {
                return ResourceManager.GetString("ru_gasstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гамбургер.
        /// </summary>
        internal static string ru_hamburger {
            get {
                return ResourceManager.GetString("ru_hamburger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хот-дог.
        /// </summary>
        internal static string ru_hot_dog {
            get {
                return ResourceManager.GetString("ru_hot_dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to л..
        /// </summary>
        internal static string ru_litres {
            get {
                return ResourceManager.GetString("ru_litres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        internal static string ru_num {
            get {
                return ResourceManager.GetString("ru_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип безина.
        /// </summary>
        internal static string ru_oil {
            get {
                return ResourceManager.GetString("ru_oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Картофель-фри.
        /// </summary>
        internal static string ru_potato {
            get {
                return ResourceManager.GetString("ru_potato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to руб..
        /// </summary>
        internal static string ru_rub {
            get {
                return ResourceManager.GetString("ru_rub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string ru_settings {
            get {
                return ResourceManager.GetString("ru_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К выдаче.
        /// </summary>
        internal static string ru_toissue {
            get {
                return ResourceManager.GetString("ru_toissue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К оплате.
        /// </summary>
        internal static string ru_topay {
            get {
                return ResourceManager.GetString("ru_topay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего к оплате.
        /// </summary>
        internal static string ru_totalpay {
            get {
                return ResourceManager.GetString("ru_totalpay", resourceCulture);
            }
        }
    }
}
